import type { AppState, Task } from "./types";
const base = {
  description: "A confirmed action from the Monday design team meeting.",
  status: "todo",
  actual_hours: 0,
  flexible: true,
  scope_saving: 0,
  version: 1,
  assigned_by: "sarah",
} as const;
const task = (
  id: string,
  title: string,
  category: string,
  estimated_hours: number,
  personalized_hours: number,
  deadline: string,
  priority: Task["priority"] = "Medium",
  employee_id = "alex",
): Task => ({
  ...base,
  id,
  title,
  category,
  estimated_hours,
  personalized_hours,
  multiplier: personalized_hours / estimated_hours,
  deadline,
  priority,
  employee_id,
});
export const previewState: AppState = {
  workspace: { id: "preview", version: 1, demo_date: "2026-09-23" },
  profiles: [
    {
      id: "alex",
      name: "Alex Morgan",
      job_title: "UX Designer",
      manager_id: "sarah",
      capacity: 30,
      weekly_hours: 40,
    },
    {
      id: "maya",
      name: "Maya Chen",
      job_title: "Researcher",
      manager_id: "sarah",
      capacity: 28,
      weekly_hours: 40,
    },
    {
      id: "jordan",
      name: "Jordan Lee",
      job_title: "Designer",
      manager_id: "sarah",
      capacity: 30,
      weekly_hours: 40,
    },
    {
      id: "sam",
      name: "Sam Patel",
      job_title: "Developer",
      manager_id: "sarah",
      capacity: 32,
      weekly_hours: 40,
    },
    {
      id: "sarah",
      name: "Sarah Lee",
      job_title: "Design Manager",
      manager_id: null,
      capacity: 30,
      weekly_hours: 40,
    },
  ],
  tasks: [
    {
      ...task(
        "presentation",
        "Client Presentation",
        "Presentation",
        8,
        9,
        "2026-09-25T08:00:00Z",
        "High",
      ),
      status: "in_progress",
      scope_saving: 2,
    },
    task(
      "research",
      "Competitor Research",
      "Research",
      6,
      7,
      "2026-09-24T10:00:00Z",
      "High",
    ),
    task(
      "testing",
      "Prototype Testing",
      "Testing",
      4,
      5,
      "2026-09-25T07:00:00Z",
    ),
    task(
      "analytics",
      "Analytics Report",
      "Analytics",
      5,
      6,
      "2026-09-23T10:00:00Z",
    ),
    task(
      "review",
      "Design Review",
      "Design",
      1,
      1,
      "2026-09-25T09:00:00Z",
      "Low",
    ),
    {
      ...task(
        "new-research",
        "Client Competitor Research",
        "Research",
        6,
        7,
        "2026-09-24T10:00:00Z",
        "High",
      ),
      status: "draft",
    },
    task(
      "maya-work",
      "Customer discovery synthesis",
      "Research",
      18,
      18,
      "2026-09-25T10:00:00Z",
      "Medium",
      "maya",
    ),
    task(
      "jordan-work",
      "Design system improvements",
      "Design",
      26,
      26,
      "2026-09-25T10:00:00Z",
      "Medium",
      "jordan",
    ),
    task(
      "sam-work",
      "Product engineering sprint",
      "Design",
      29,
      29,
      "2026-09-25T10:00:00Z",
      "High",
      "sam",
    ),
  ],
  subtasks: [
    "Review analytics with John",
    "Collect relevant data",
    "Draft presentation",
    "Add visuals",
    "Review slides",
    "Finalize and send",
  ].map((title, i) => ({
    id: `presentation-${i}`,
    task_id: "presentation",
    title,
    completed: i < 2,
    minutes: [20, 20, 130, 100, 50, 40][i],
    position: i,
  })),
  history: [
    "Presentation",
    "Research",
    "Testing",
    "Analytics",
    "Design",
  ].flatMap((category, i) =>
    [0, 1, 2].map((j) => ({
      id: `history-${i}-${j}`,
      employee_id: "alex",
      task_id: null,
      category,
      estimated_hours: [8, 6, 4, 5, 1][i],
      actual_hours: [9, 7, 5, 6, 1][i],
      completed_at: `2026-09-${18 - j}T10:00:00Z`,
    })),
  ),
  negotiations: [],
  messages: [],
  dependencies: [],
};
